ERP.Web/Areas/HRManagement/Controllers/PaySlipController.cs
using ERP.Core.Models.HRManagement;
using ERP.Service.Interfaces.GeneralManagement;
using ERP.Web.Controllers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ERP.Web.Areas.HRManagement.Controllers
{
    public class PaySlipController : BaseController
    {
        IDropDownService iDropDown = null;

        public PaySlipController(IDropDownService iDropDownService)
        {
            iDropDown = iDropDownService;
        }
        // GET: HRManagement/PaySlip
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult List()
        {
            return PartialView(new PaySlip());
        }

        public ActionResult Create()
        {
            ViewBag.EmployeeList = new SelectList(iDropDown.GetDropDowns("employee"), "Id", "DisplayName");

            return PartialView(new PaySlip());
        }

        #region slipDetails
        public ActionResult slipDetails()
        {
            ViewBag.Earnings = new SelectList(iDropDown.GetDropDowns("get-earnings"), "Id", "DisplayName");
            ViewBag.Deductions = new SelectList(iDropDown.GetDropDowns("get-deductions"), "Id", "DisplayName");

            PaySlipDetail obj = new PaySlipDetail();
            return PartialView(obj);
        }
        #endregion


    }
}

ERP.Web/Areas/HRManagement/Views/PaySlip/Create.cshtml
@model ERP.Core.Models.HRManagement.PaySlip

<div class="form">
    <div class="card">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary"> Create Pay Slip</h6>
        </div>

        <div class="card-body">
            @using (Html.BeginForm("Create", "PaySlip", FormMethod.Post, new { enctype = "multipart/form-data", onSubmit = "return JQueryAjaxPost(this);", data_restUrl = Url.Action("Create", "PaySlip"), @class = "form-horizontal", id = "PaySlip-form" }))//data-resetUrl
            {
                @Html.AntiForgeryToken()

                <div class="form-row">
                    <div class="form-group col-md-4">
                        @Html.LabelFor(model => model.EmployeeId, "Employee", new { @class = "form-control-label required" })
                        @Html.DropDownListFor(model => model.EmployeeId, (SelectList)ViewBag.EmployeeList, "--Select--", new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.EmployeeId, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group col-md-2">
                        @Html.LabelFor(model => model.Year, new { @class = "form-control-label required" })
                        @Html.TextBoxFor(model => model.Year, new { @class = "form-control", @type = "number" })
                    </div>

                    <div class="form-group col-md-2">
                        @Html.LabelFor(model => model.Month, new { @class = "form-control-label required" })
                        @Html.DropDownListFor(Model => Model.Month, new List<SelectListItem>
                                                    {
                                                          new SelectListItem {Text="January",Value="1" },
                                                          new SelectListItem {Text="February",Value="2" },
                                                          new SelectListItem { Text="March",Value="3"},
                                                          new SelectListItem { Text="April",Value="4"},
                                                          new SelectListItem { Text="May",Value="5"},
                                                          new SelectListItem { Text="June",Value="6"},
                                                          new SelectListItem { Text="July",Value="7"},
                                                          new SelectListItem { Text="August",Value="8"},
                                                          new SelectListItem { Text="September",Value="9"},
                                                          new SelectListItem { Text="October",Value="10"},
                                                          new SelectListItem { Text="November",Value="11"},
                                                          new SelectListItem { Text="December",Value="12"},

                                                     }, "--Select Months--", new { @class = "form-control", id = "Month" })
                        @Html.ValidationMessageFor(model => model.Month, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group col-md-4">
                        <br />
                        <button type="button" class="btn btn-primary btn-lg btn-block"> GO </button>
                    </div>
                </div>

            }
        </div>

        <br />
        <div id="slipDetails">



        </div>
    </div>
</div>


<script>

    $(document).ready(function () {
        var d = new Date();
        var n = d.getFullYear();
        $("#Year").val(n);

        //$("#slipDetails").hide();
        bindView('@Url.Action("slipDetails", "PaySlip")', 'slipDetails')

    });





</script>

<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

ERP.Web/Areas/HRManagement/Views/PaySlip/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Html.Partial("~/Views/_ViewLookupTab.cshtml")

<script type="text/javascript">
      $(document).ready(function () {
            bindView('@Url.Action("List", "PaySlip")', 'list')
            setTimeout(function () {
                LoadTabs();
            }, 1000);
            function LoadTabs() {
                bindView('@Url.Action("Create", "PaySlip")', 'addedit')
            }
    });


        $('#templatemo-tabs a').click(function (e) {
            var id = $(this).attr('href');
                switch (id) {
                    case "#list":
                        bindView('@Url.Action("List", "PaySlip")', 'list')
                        if ($('ul.nav.nav-tabs a:eq(1)').text()=="Update")
                        {
                             $('ul.nav.nav-tabs a:eq(1)').html('Add');
                             bindView('@Url.Action("Create", "PaySlip")', 'addedit')
                        }
                        break;
                    case "#addedit":
                        bindView('@Url.Action("Create", "PaySlip")', 'addedit')
                        break;
                    default:
                }
        });
</script>

ERP.Web/Areas/HRManagement/Views/PaySlip/slipDetails.cshtml
@model ERP.Core.Models.HRManagement.PaySlipDetail

<div class="row">

    <div class="col-md-6">
        <h3>Earnings </h3>

        <table class="table" id="tblEarnings">
            <thead class="table-dark">
                <tr>
                    <td>Earnings</td>
                    <td>Amount</td>
                    <td>Action</td>
                </tr>
            </thead>

            <tbody>
                <tr>
                    <td>
                        @Html.DropDownList("Earnings", (SelectList)ViewBag.Earnings, "Select", new { @class = "form-control", @id = "earning" })
                    </td>
                    <td>
                        @Html.TextBox("Amount", "", new { @class = "form-control", @id = "earning-amount", onkeypress = "return isNumeric(event)" })
                    </td>
                    <td>
                        <button type="button" class="btn btn-primary btn-sm" id="btn-AddEarning" rel="tooltip" title="Add">
                            <i class="fa fa-plus"></i>
                        </button>
                        <button type="button" id="EarningEditBtn" rel="tooltip" title="Update" class="btn btn-info btn-sm" style="display:none;" onclick="UpdateEarningRow(this)" name="EarningEditBtn"><i class="fa fa-check-square-o"></i> </button>
                        <button type="button" class="btn btn-danger btn-sm" id="btn-clearEarnings" rel="tooltip" title="Clear">
                            <i class="fa fa-stop"></i>
                        </button>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>

    <div class="col-md-6">
        <h3>Deductions </h3>

        <table class="table" id="tblDeduction">
            <thead class="table-dark">
                <tr>
                    <td>Deductions</td>
                    <td>Amount</td>
                    <td>Action</td>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                        @Html.DropDownList("Deductions", (SelectList)ViewBag.Deductions, "Select", new { @class = "form-control", @id = "deductions" })
                    </td>
                    <td>
                        @Html.TextBox("Amount", "", new { @class = "form-control", @id = "deducted-amount", onkeypress = "return isNumeric(event)" })
                    </td>
                    <td>
                        <button type="button" class="btn btn-primary btn-sm" id="btn-AddDeduction" rel="tooltip" title="Add">
                            <i class="fa fa-plus"></i>
                        </button>
                        <button type="button" id="DeductionEditBtn" rel="tooltip" title="Update" class="btn btn-info btn-sm" style="display:none;" onclick="UpdateDeductionRow(this)" name="DeductionEditBtn"><i class="fa fa-check-square-o"></i> </button>
                        <button type="button" class="btn btn-danger btn-sm" id="btn-clearDeductions" rel="tooltip" title="Clear">
                            <i class="fa fa-stop"></i>
                        </button>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>

</div>



<script src="~/Scripts/App/PaySlip.js"></script>