ERP.Web/Areas/HRManagement/Controllers/LeaveApplicationController.cs
using ERP.Core.Models.HRManagement;
using ERP.Service.Interfaces.GeneralManagement;
using ERP.Service.Interfaces.HRManagement;
using ERP.Web.Controllers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ERP.Web.Areas.HRManagement.Controllers
{
    public class LeaveApplicationController : BaseController
    {
        IDropDownService iDropDownService;
        ILeaveService ileave;

        public LeaveApplicationController(IDropDownService dropDownService, ILeaveService leaveService)
        {
            iDropDownService = dropDownService;
            ileave = leaveService;
        }
        // GET: HRManagement/LeaveApplication
        public ActionResult Index()
        {
            return PartialView();
        }

        public ActionResult List()
        {
            List<LeaveApplicationVM> lst = ileave.AllList();
            return PartialView(lst);
        }

        public ActionResult Create()
        {
            ViewBag.Department = new SelectList(iDropDownService.GetDropDowns("department"), "Id", "DisplayName");
            return PartialView(new LeaveApplication());
        }

        [HttpPost]
        public ActionResult Create(LeaveApplication obj)
        {
            if(ModelState.IsValid)
            {
                try
                {
                    var result = ileave.Update(obj, "i");
                    return Json(new
                    {
                        ErrorCode = result.ErrorCode,
                        Message = result.Msg,
                        Id = result.Id,
                        JsonRequestBehavior.AllowGet
                    });
                }
                catch(Exception ex)
                {
                    return Json(new { ErrorCode = 1, Message = ex.Message }, JsonRequestBehavior.AllowGet);
                }
            }

            Response.TrySkipIisCustomErrors = true;
            string messages = string.Join("; ", ModelState.Values
                                        .SelectMany(x => x.Errors)
                                        .Select(x => x.ErrorMessage));
            return Json(new { ErrorCode = 1, Message = messages }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Edit(string id)
        {
            ViewBag.Department = new SelectList(iDropDownService.GetDropDowns("department"), "Id", "DisplayName");
            ViewBag.Employee = new SelectList(iDropDownService.GetDropDowns("employee"), "Id", "DisplayName");

            LeaveApplication obj = ileave.GetById(id);
            return PartialView(obj);
        }

        [HttpPost]
        public ActionResult Edit(LeaveApplication obj)
        {
            if(ModelState.IsValid)
            {
                try
                {
                    var result = ileave.Update(obj, "u");
                    return Json(new
                    {
                        ErrorCode = result.ErrorCode,
                        Message = result.Msg,
                        Id = result.Id,
                        JsonRequestBehavior.AllowGet
                    });
                }
                catch(Exception ex)
                {
                    return Json(new { ErrorCode = 1, Message = ex.Message }, JsonRequestBehavior.AllowGet);
                }
            }
            Response.TrySkipIisCustomErrors = true;
            string messages = string.Join("; ", ModelState.Values
                                        .SelectMany(x => x.Errors)
                                        .Select(x => x.ErrorMessage));
            return Json(new { ErrorCode = 1, Message = messages }, JsonRequestBehavior.AllowGet);
        }


        [HttpPost]
        public ActionResult Delete(string id)
        {
            try
            {
                var result = ileave.Delete(id);
                return Json(new
                {
                    ErrorCode = result.ErrorCode,
                    Message = result.Msg,
                    Id = result.Id,
                    JsonRequestBehavior.AllowGet
                });
            }
            catch(Exception ex)
            {
                return Json(new { ErrorCode = 1, Message = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public ActionResult Action(string id, string type)
        {
            try
            {
                var result = ileave.LeaveAction(id,type);
                return Json(new
                {
                    ErrorCode = result.ErrorCode,
                    Message = result.Msg,
                    Id = result.Id,
                    JsonRequestBehavior.AllowGet
                });
            }
            catch(Exception ex)
            {
                return Json(new { ErrorCode = 1, Message = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        public JsonResult GetEmployee(string id)
        {
            var Emp = iDropDownService.GetDropDowns("employee", id).Select(r => new { value = r.Id, text = r.DisplayName });
            return Json(Emp, JsonRequestBehavior.AllowGet);
        }



    }
}

ERP.Web/Areas/HRManagement/Views/LeaveApplication/Create.cshtml
@model ERP.Core.Models.HRManagement.LeaveApplication

<div class="form">
    <div class="card">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary"> Create Leave Request</h6>
        </div>

        <div class="card-body">
            @using (Html.BeginForm("Create", "LeaveApplication", FormMethod.Post, new { enctype = "multipart/form-data", onSubmit = "return JQueryAjaxPost(this);", data_restUrl = Url.Action("Create", "LeaveApplication"), @class = "form-horizontal", id = "LeaveApplication-form" }))//data-resetUrl
            {
                @Html.AntiForgeryToken()
                <div class="form-row">

                    <div class="form-group col-md-6">
                        @Html.LabelFor(model => model.DepartmentId, "Department", new { @class = "form-control-label required" })
                        @Html.DropDownListFor(model => model.DepartmentId, (SelectList)ViewBag.Department, "--" + "Select" + "--", new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.DepartmentId, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group col-md-6">
                        @Html.LabelFor(model => model.EmpId, "Employee", new { @class = "form-control-label required" })
                        @Html.DropDownListFor(model => model.EmpId, new SelectList("", "", ""), "--Select--", new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.EmpId, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-6 ">
                        <label class="small mb-1 required" for="inputOrgName">Leave Type</label>
                        @Html.DropDownListFor(Model => Model.Reason, new List<SelectListItem>
                                                   {
                                                         new SelectListItem {Text="Personal Leave",Value="Personal Leave" },
                                                         new SelectListItem {Text="Emergency Leave",Value="Emergency Leave" },
                                                         new SelectListItem { Text="Sick Leave",Value="Sick Leave"},
                                                         new SelectListItem { Text="Others",Value="Others"},

                                                    }, "--Select Type--", new { @class = "form-control"  })
                        @Html.ValidationMessageFor(model => model.LeaveType, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group col-md-6 ">
                        <label class="small mb-1 required" for="inputOrgName">Leave Category</label>
                        @Html.DropDownListFor(Model => Model.LeaveType, new List<SelectListItem>
                                                   {
                                                         new SelectListItem {Text="Full Day",Value="Full Day" },
                                                         new SelectListItem {Text="Half Day",Value="Half Day" },
                                                         
                                                    }, "--Select Category--", new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.LeaveType, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-6">
                        @Html.LabelFor(model => model.StartDate, "Start Date", new { @class = "form-control-label required" })
                        @Html.TextBoxFor(model => model.StartDate, " ", new { @class = "form-control", @type = "date", @Value = @DateTime.Now.ToShortDateString() })
                        @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group col-md-6">
                        @Html.LabelFor(model => model.EndDate, "End Date", new { @class = "form-control-label required" })
                        @Html.TextBoxFor(model => model.EndDate, " ", new { @class = "form-control", @type = "date", @Value = @DateTime.Now.ToShortDateString() })
                        @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
                    </div>
                </div>

             
                
                <div class="form-row">
                    <div class="form-group col-md-12 ">
                        <label class="small mb-1 required" for="inputOrgName">Reason</label>
                        @Html.TextAreaFor(model => model.Remarks, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Remarks, "", new { @class = "text-danger" })
                    </div>
                </div>
                
                <div class="form-group row">
                    <div class="col-sm-10">
                        <button class="btn btn-success btn-lg" type="submit" id="btn-submit">Save</button>
                        <button class="btn btn-danger btn-lg" type="button" id="btn-clear">Clear</button>
                    </div>
                </div>

            }
        </div>
    </div>
</div>


<script>

    $(document).ready(function () {
        BindCascadeDropdown('@Url.Action("GetEmployee")', 'DepartmentId', 'EmpId');
    });


    $('#btn-clear').on('click', function () {
        GlobalFunctions.ClearForm($(this))
    });

</script>

<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

ERP.Web/Areas/HRManagement/Views/LeaveApplication/Edit.cshtml
@model ERP.Core.Models.HRManagement.LeaveApplication

<div class="form">
    <div class="card">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary"> Edit Leave Request</h6>
        </div>

        <div class="card-body">
            @using (Html.BeginForm("Edit", "LeaveApplication", FormMethod.Post, new { enctype = "multipart/form-data", onSubmit = "return JQueryAjaxPost(this);", data_restUrl = Url.Action("Edit", "LeaveApplication"), @class = "form-horizontal", id = "LeaveApplication-form" }))//data-resetUrl
            {
                @Html.AntiForgeryToken()
                @Html.HiddenFor(model => model.Id)

                <div class="form-row">

                    <div class="form-group col-md-6">
                        @Html.LabelFor(model => model.DepartmentId, "Department", new { @class = "form-control-label required" })
                        @Html.DropDownListFor(model => model.DepartmentId, (SelectList)ViewBag.Department, "--" + "Select" + "--", new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.DepartmentId, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group col-md-6">
                        @Html.LabelFor(model => model.EmpId, "Employee", new { @class = "form-control-label required" })
                        @Html.DropDownListFor(model => model.EmpId, (SelectList)ViewBag.Employee, "--" + "Select" + "--", new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.EmpId, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-6 ">
                        <label class="small mb-1 required" for="inputOrgName">Leave Type</label>
                        @Html.DropDownListFor(Model => Model.Reason, new List<SelectListItem>
                                                   {
                                                         new SelectListItem {Text="Personal Leave",Value="Personal Leave" },
                                                         new SelectListItem {Text="Emergency Leave",Value="Emergency Leave" },
                                                         new SelectListItem { Text="Sick Leave",Value="Sick Leave"},
                                                         new SelectListItem { Text="Others",Value="Others"},

                                                    }, "--Select Type--", new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.LeaveType, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group col-md-6 ">
                        <label class="small mb-1 required" for="inputOrgName">Leave Category</label>
                        @Html.DropDownListFor(Model => Model.LeaveType, new List<SelectListItem>
                                                   {
                                                         new SelectListItem {Text="Full Day",Value="Full Day" },
                                                         new SelectListItem {Text="Half Day",Value="Half Day" },

                                                    }, "--Select Category--", new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.LeaveType, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-6">
                        @Html.LabelFor(model => model.StartDate, "Start Date", new { @class = "form-control-label required" })
                        @Html.TextBoxFor(model => model.StartDate, "{0:yyyy-MM-dd}", new { @class = "form-control", @type = "date"})
                        @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group col-md-6">
                        @Html.LabelFor(model => model.EndDate, "End Date", new { @class = "form-control-label required" })
                        @Html.TextBoxFor(model => model.EndDate, "{0:yyyy-MM-dd}", new { @class = "form-control", @type = "date" })
                        @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-12 ">
                        <label class="small mb-1 required" for="inputOrgName">Reason</label>
                        @Html.TextAreaFor(model => model.Remarks, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Remarks, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-sm-10">
                        <button class="btn btn-success btn-lg" type="submit" id="btn-update">Update</button>
                        <button class="btn btn-danger btn-lg" type="button" id="btn-cancel">Cancel</button>
                    </div>
                </div>

             }
        </div>
    </div>
</div>


<script>

     $('#btn-cancel').on('click', function () {
            CancelUpdate("@Url.Action("Create", "LeaveApplication")","@Url.Action("List", "LeaveApplication")");
     });

    $(document).ready(function () {
        BindCascadeDropdownEdit('@Url.Action("GetEmployee")', 'DepartmentId', 'EmpId');
    });

</script>

<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

ERP.Web/Areas/HRManagement/Views/LeaveApplication/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Html.Partial("~/Views/_ViewLookupTab.cshtml")

<script type="text/javascript">
      @*$(document).ready(function () {
            bindView('@Url.Action("List", "LeaveApplication")', 'list')
            setTimeout(function () {
                LoadTabs();
            }, 1000);
            function LoadTabs() {
                bindView('@Url.Action("Create", "LeaveApplication")', 'addedit')
            }
    });*@


        $('#templatemo-tabs a').click(function (e) {
            var id = $(this).attr('href');
                switch (id) {
                    case "#list":
                        bindView('@Url.Action("List", "LeaveApplication")', 'list')
                        if ($('ul.nav.nav-tabs a:eq(1)').text()=="Update")
                        {
                             $('ul.nav.nav-tabs a:eq(1)').html('Add');
                             bindView('@Url.Action("Create", "LeaveApplication")', 'addedit')
                        }
                        break;
                    case "#addedit":
                        bindView('@Url.Action("Create", "LeaveApplication")', 'addedit')
                        break;
                    default:
                }
        });
</script>

ERP.Web/Areas/HRManagement/Views/LeaveApplication/List.cshtml
@model List<ERP.Core.Models.HRManagement.LeaveApplicationVM>


<div class="col-md-12">
    <div class="card">

        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Leave Info</h6>
            </div>

            <div class="card-body">
                <div class="table-responsive">

                    <table class="table" id="dataTable" width="100%" cellspacing="0">
                        <thead class="thead-dark">

                            <tr>
                                <th>SN</th>
                                <th>Name</th>
                                <th>Department</th>
                                <th>Reason</th>
                                <th>Type</th>
                                <th>From</th>
                                <th>To</th>
                                <th>Remarks</th>
                                <th>Status</th>

                                <th>Action</th>
                            </tr>
                        </thead>

                        @if (Model != null)
                        {
                            int count = 1;
                            <tbody>
                                @foreach (var item in Model.OrderBy(x => x.Status))
                                {
                                    <tr>
                                        <td width="5%">@count</td>
                                        <td>@item.EmployeeName</td>
                                        <td>@item.Department</td>
                                        <td>@item.Reason</td>
                                        <td>@item.LeaveType</td>
                                        <td>@ERP.Common.Helper.GlobalHelper.ToShortDate(item.StartDate.ToString())</td>
                                        <td>@ERP.Common.Helper.GlobalHelper.ToShortDate(item.EndDate.ToString())</td>
                                        <td>@item.Remarks</td>

                                        @if (item.Status == "Pending")
                                        {
                                            <td style="color:blue">@item.Status</td>
                                        }
                                        else if (item.Status == "Approved")
                                        {
                                            <td style="color:green">@item.Status</td>
                                        }
                                        else
                                        {
                                            <td style="color:red">@item.Status</td>
                                        }

                                        <td width="10%">
                                            <a title="Edit" onclick='return Action("@Url.Action("Edit","LeaveApplication")","edit","@item.Id")' href='#' id='btn_@item.Id' style="color:green"><i class="fas fa-edit" style="font-size:20px"></i></a>
                                            <a title="Delete" onclick='return Action("@Url.Action("Delete","LeaveApplication")","delete","@item.Id")' href='#' id='btn_@item.Id' style=" color: #FF0000;"><i class="far fa-trash-alt" style="font-size:20px"></i></a>
                                            <a title="Action" onclick='return CustomAction("@Url.Action("Action","LeaveApplication")","@item.Id")' href='#' id='btn_@item.Id' style=" color: #feb405;"><i class="fas fa-dharmachakra" style="font-size:20px"></i></a>

                                        </td>
                                    </tr>
                                    count++;
                                }
                            </tbody>

                        }
                        else
                        {
                            <tbody>
                                <tr>
                                    No data to show
                                </tr>
                            </tbody>
                        }
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>


<script>

    function ajaxPost(url, id, gridUrl, action) {
        var list_tab_id = "list";

        $.ajax({
            type: "POST",
            url: url,
            data: { "id": id, "type": action },
            dataType: "json",
            success: function (data) {

                if (data.ErrorCode == 0) //refresh grid
                {
                    bindView(gridUrl, list_tab_id);
                }
                GlobalFunctions.GetMessage(data.Message, null, data.ErrorCode, 0, null, null);
                return;
            },
            error: function () {
                GlobalFunctions.GetMessage("error occurred", null, "1", 0, null, null);
                return;
            }
        });
    }

    function CustomAction(url, id, gridUrl) {

        bootbox.dialog({
            //title: 'Leave Action',
            message: "<p>Please perform the required action for the leave request.</p>",
            size: 'large',
            buttons: {
                reject: {
                    label: "Reject",
                    className: 'btn-danger',
                    callback: function () {

                        ajaxPost(url, id, gridUrl, "Rejected"); 

                    }
                },
                pending: {
                    label: "Pending",
                    className: 'btn-warning',
                    callback: function () {
                        ajaxPost(url, id, gridUrl, "Pending"); 
                    }
                },
                accept: {
                    label: "Approve",
                    className: 'btn-success',
                    callback: function () {
                        ajaxPost(url, id, gridUrl, "Approved"); 
                    }
                },
                cancel: {
                    label: "Cancel",
                    className: 'btn-info',
                    callback: function () {
                        console.log('Custom button clicked');
                        return;
                    }
                }
            },
           
        });

    };

</script>